"""Writes assets/world1/README.md from the sheet manifest, so the frame lists
and timings in the README can never drift from the PNGs."""
import os

INTRO = """# World 1 and World 2 art

Sprite sheets for every World 1 tile, trap, enemy, pickup and effect, plus the
Gate transmitter backdrop. The World 2 (The Switchyard) sheets come after them,
in the same folder and pipeline. Generated by `src/make_sheets.py` (Python +
Pillow).

## Rules the art follows

- Four greys only: `#0b0b0b` `#3a3a3a` `#8a8a8a` `#f2f2f2`, plus transparency.
  The generator refuses to write a pixel of any other colour.
- 16 px tiles, drawn for a 480x270 canvas with nearest-neighbour scaling.
- White means alive or important: lit lips you can stand on, pickups, the one
  lamp on a dead panel. Backdrops stay dark.
- Danger is shown by shape and motion: teeth, cracks, jitter and blink frames.
  Every enemy and trap has a 2 to 3 frame warning ("tell") before it acts.
- Dither uses the same 4x4 Bayer matrix as `scripts/draw_util.gd`. Every frame
  is 16 px aligned, so the pattern lines up with world coordinates and never
  swims when the camera scrolls.
- The Spark is not in these sheets. It stays the coded white block from
  `scripts/spark_visual.gd`. Effects around it (dash ghosts, dust, CHARGE glow)
  are here or in `scripts/world1/juice.gd`.

## How to read a sheet

Each row is one animation, or one set of static variants. Frames run left to
right. `sheets.json` and `scripts/world1/sheet_data.gd` hold the same data:
frame size, the row of each animation, its frame count, the time each frame is
shown (seconds) and whether it loops. A time of 0 means a static frame.

All sprites face left. Mirror them for right. Unless a note says otherwise,
draw a sprite with its top-left on the tile's top-left. Bigger sprites say
where they anchor in their note.

## Regenerate, view, capture

- Regenerate: `python assets/world1/src/make_sheets.py` from the project root.
- View: open `scenes/world1_showcase.tscn` and press F6. Left and right change
  page. F toggles the screen shader, S shakes the screen, T is slow motion,
  P pauses, Space restarts the loops, Up and Down change level on the last page.
- Capture: `"E:/Godot games/Godot_v4.7.2-stable_win64.exe" --path . --resolution 960x540 --script res://scripts/world1/showcase_capture.gd`
  writes PNGs to `test-user/world1-art/`.

## Code that goes with the art

- `scripts/world1/sheets.gd` loads every sheet and draws a frame by sheet and
  animation name, with the manifest's timing. Mirrored frames use a pre-flipped
  copy of the sheet.
- `scripts/world1/juice.gd` holds the effects as plain functions of time:
  screen shake, hit-stop, particles, dust, grit, speed lines, glints, dash
  ghosts and the Spark itself. No random numbers, so every effect replays the
  same way and can be captured frame by frame.
- `shaders/world1/signal_crt.gdshader` is the optional screen pass: a soft
  bloom on white only, scanlines on the game's own pixel rows, dark edges.
- `scripts/world1/level_view.gd` draws the real `levels/world1/*.txt` maps with
  these tiles. It reads the same legend and `[objects]` timings as
  `tools/levels/levelkit.py`.

## Sheets
"""


WORLD2 = """## World 2 sheets: The Switchyard

A dead relay yard where the broadcast line splits into two channels. Channel
ONE is always marked with horizontal bars and channel TWO with a diamond, on
the blocks, the switch and the relay boss. `ground_w2` and `block_w2` use the
same animation names and columns as `ground` and `block`, so a level can swap
one set for the other. Hazards keep white to a pixel or two (tooth tips,
sparks), because solid white is the Spark's colour.
"""


ATMOSPHERE = """## Atmosphere sheets

Lamps, light, weather and fog for dark stretches, usable in any world. The
lamp is the only one of these with white you can see in the sprite itself.

`light_mask` is a mask, not art. White means lit and transparent means unlit.
The game uses it to cut the darkness away around a light, so it must never be
drawn on screen as colour. Its frames are 256x256, not 128x128, because a
radius of 120 needs a 240 px wide disc.
"""


VILLAGE = """## Village sheets: Last Relay

Last Relay is the hub village, built into a relay station that still works. It
is quiet, with a few lit windows, and you come back to it between levels. The
villagers are "listeners", small radio folk who kept the last relay running.
They are grey and dark with two small white dot eyes, round tops and no teeth,
so they never read as the white striped enemies.

Three story signatures recur here: the window with one broken diagonal mullion
(the keeper's house), the notched isolation handle (Brace's belt, the switch
hut wall) and the two-part maintenance mark (by doors, on a crate, on the
schematic).

Where an animation's art is smaller than its sheet's frame (the house door,
the 8x8 bubble parts), the art sits at the frame's top-left and the rest is
transparent. Draw the frame at the art's own top-left.
"""


def _fmt_dur(d):
    if all(x == 0 for x in d):
        return 'static'
    if len(set(d)) == 1:
        return f'{d[0]:g} s each'
    return ' / '.join(f'{x:g}' for x in d) + ' s'


def write(sheets, out_dir, sections=None):
    """`sections` maps a sheet name to a block of text written just before it."""
    lines = [INTRO]
    for name, s in sheets.items():
        if sections and name in sections:
            lines.append(sections[name])
        lines.append(f"### {name}.png ({s['fw']}x{s['fh']} frames)\n")
        lines.append(s['about'] + '\n')
        lines.append('| Row | Animation | Frames | Timing | Loops | Notes |')
        lines.append('|---|---|---|---|---|---|')
        for anim in s['order']:
            a = s['anims'][anim]
            loop = 'yes' if a['loop'] and any(a['dur']) else 'no'
            if not any(a['dur']):
                loop = ''
            note = a['note'].replace('|', '/')
            lines.append(f"| {a['row']} | {anim} | {a['frames']} | {_fmt_dur(a['dur'])} | {loop} | {note} |")
        lines.append('')
    with open(os.path.join(out_dir, 'README.md'), 'w', encoding='utf-8', newline='\n') as fh:
        fh.write('\n'.join(lines))
