extends SceneTree
func _initialize() -> void: run.call_deferred()
func run() -> void:
    var world = load("res://scenes/exploration.tscn").instantiate()
    world.save_path = "res://test-user/map-revisit-%d.json" % OS.get_process_id()
    root.add_child(world)
    assert(world.map_state("fourth") == "hidden")
    assert(world.map_note("fourth").is_empty())
    assert(world.profile.enter_room("amplifier"))
    assert(world.map_state("fourth") == "hint")
    assert(world.map_note("fourth") == "AIR JUMP NEEDED")
    assert(world.profile.set_flag("air_jump"))
    assert(world.map_note("fourth") == "REACHABLE")
    assert(world.map_state("fourth") == "hint")
    assert(world.profile.enter_room("fourth"))
    assert(world.map_note("fourth") == "SIGNAL UNREAD")
    assert(world.profile.set_flag("fourth_archive"))
    assert(world.map_note("fourth") == "ARCHIVE")
    # Hints do not reveal project state before the room has been visited.
    assert(world.profile.enter_room("wire_shelter"))
    assert(world.map_state("wire_carriage") == "hint")
    assert(world.map_note("wire_carriage").is_empty())
    for room_id in ["pump","wire_carriage","array","sump","stand_trial","array_shutter"]:
        assert(world.profile.enter_room(room_id))
    assert(world.map_note("pump") == "PART NEEDED")
    assert(world.profile.set_flag("impeller"))
    assert(world.map_note("pump") == "FIT IMPELLER")
    assert(world.profile.set_flag("pump_repaired"))
    assert(world.map_note("pump") == "PUMP LIVE")
    assert(world.map_note("wire_carriage") == "PART NEEDED")
    assert(world.profile.set_flag("brake_spare"))
    assert(world.map_note("wire_carriage") == "FIT BRAKE")
    assert(world.profile.set_flag("wire_repaired"))
    assert(world.map_note("wire_carriage") == "REPAIRED")
    assert(world.map_note("array") == "TEST FEED")
    assert(world.profile.set_flag("diagnostic_seen"))
    assert(world.map_note("array") == "ISOLATE FAULT")
    assert(world.profile.set_flag("array_isolated"))
    assert(world.map_note("array") == "ROUTE FEED")
    assert(world.profile.set_flag("array_restored"))
    assert(world.map_note("array") == "FEED LIVE")
    assert(world.map_note("sump") == "EARS NEEDED")
    assert(world.profile.set_flags({"west_ear":true,"east_ear":true,"south_ear":true}))
    assert(world.map_note("sump") == "COMMISSION")
    assert(world.map_note("stand_trial") == "SIGNAL UNREAD")
    assert(world.map_note("array_shutter") == "SIGNAL UNREAD")
    assert(world.profile.set_flag("stand_archive"))
    assert(world.map_note("stand_trial") == "ARCHIVE")
    assert(world.profile.load_profile())
    assert(world.map_note("array") == "FEED LIVE")
    var saved := FileAccess.get_file_as_bytes(world.save_path)
    for i in 10:
        for room_id in world.profile.data.visited: world.map_note(room_id)
    assert(FileAccess.get_file_as_bytes(world.save_path) == saved)
    var path: String = world.save_path
    world.queue_free()
    await process_frame
    for suffix in ["", ".tmp", ".bak"]: DirAccess.remove_absolute(path+suffix)
    print("MAP REVISIT: hidden, gated, reachable, unread and archived; read-only passed")
    quit()
