extends "res://scripts/exploration_routes_test.gd"
## Input route through the integrated expanded Stand, with an isolated profile.
func press_use() -> void:
    var event := InputEventKey.new()
    event.keycode = KEY_E
    event.pressed = true
    Input.parse_input_event(event)
    await frames(3)
    event = InputEventKey.new()
    event.keycode = KEY_E
    event.pressed = false
    Input.parse_input_event(event)
    await frames(3)
func run() -> void:
    scene = load("res://scenes/exploration.tscn").instantiate()
    scene.save_path = "res://test-user/stand_campaign_routes.json"
    for suffix in ["", ".tmp", ".bak"]: DirAccess.remove_absolute(scene.save_path+suffix)
    root.add_child(scene)
    scene.enter_room("stand_rim")
    if "--upgraded" in OS.get_cmdline_user_args():
        root.get_node("RunState").mods.dash = true
        root.get_node("RunState").mods.air_jumps = 1
        scene.player.reset_at(scene.player.position)
    await frames(5)
    await land(180,217,false)
    await land(340,217,false)
    await land(445,217,false)
    await press_use()
    await land(78,217,false)
    await land(140,183)
    await land(160,183,false)
    await land(235,149)
    await land(266,149,false)
    await land(345,115)
    await land(365,115,false)
    await press_use()
    await land(76,217,false)
    await land(140,183)
    await land(164,183,false)
    await land(240,149)
    await press_use()
    await frames(185)
    await land(280,149,false)
    await land(353,149)
    await land(436,149,false)
    await press_use()
    await land(72,217,false)
    await land(128,183)
    await land(154,183,false)
    await land(225,151)
    await land(256,151,false)
    await land(347,151)
    await land(365,151,false)
    await press_use()
    if "--interrupt" in OS.get_cmdline_user_args():
        await frames(20)
        var reset_event := InputEventKey.new()
        reset_event.keycode = KEY_R
        reset_event.pressed = true
        Input.parse_input_event(reset_event)
        await frames(130)
        print("INTERRUPTION OBSERVATION: room=",scene.room_id," charge=",scene.stand.charge," cycle=",scene.stand.timer," latched=",scene.profile.has_flag("stand_restored"))
        print("STAND MOVEMENT STUDY: %d missed landings" % failed)
        quit(1 if failed else 0)
        return
    await frames(120)
    print("MOTOR OBSERVATION: latched=",scene.profile.has_flag("stand_restored")," room=",scene.room_id)
    await land(439,151,false)
    await press_use()
    await land(270,217,false)
    await land(110,217,false)
    await land(27,217,false)
    await press_use()
    print("RETURN OBSERVATION: room=",scene.room_id," latched=",scene.profile.has_flag("stand_restored"))
    # Reverse the whole loop using existing exits and base jumps.
    await land(447,217,false)
    await press_use()
    await land(200,217,false)
    await land(370,217,false)
    await land(447,217,false)
    await press_use()
    await land(345,151,false)
    await land(235,151)
    await land(130,183,false)
    await land(27,217,false)
    await press_use()
    await land(350,149,false)
    await land(245,149)
    await land(140,183,false)
    await land(27,217,false)
    await press_use()
    await land(250,149,false)
    await land(140,183,false)
    await land(40,217,false)
    print("REVERSE OBSERVATION: room=",scene.room_id," latched=",scene.profile.has_flag("stand_restored"))
    var recovery := InputEventKey.new()
    recovery.keycode = KEY_R
    recovery.pressed = true
    Input.parse_input_event(recovery)
    await frames(5)
    print("RECOVERY OBSERVATION: room=",scene.room_id," charge=",scene.stand.charge," latched=",scene.profile.has_flag("stand_restored"))
    await land(200,217,false)
    await land(240,217,false)
    await press_use()
    await land(158,149,false)
    await land(279,183,false)
    await land(420,217,false)
    await press_use()
    print("SLUICE OBSERVATION: room=",scene.room_id," message=",scene.notice)
    await land(345,217,false)
    await land(286,183)
    await land(251,183,false)
    await land(180,149)
    await land(141,149,false)
    await land(73,115)
    await land(32,115,false)
    await press_use()
    print("SLUICE RETURN: room=",scene.room_id)
    if scene.room_id != "shelter" or not scene.profile.has_flag("stand_restored"):
        failed += 1
        print("FAIL route must finish in shelter with feeder restored")
    scene.queue_free()
    await process_frame
    for suffix in ["", ".tmp", ".bak"]: DirAccess.remove_absolute("res://test-user/stand_campaign_routes.json"+suffix)
    print("EXPANDED STAND ROUTES: %d failures" % failed)
    quit(1 if failed else 0)
