extends RefCounted
## Generated by assets/world1/src/make_sheets.py. Do not edit by hand.
## sheet -> {file, fw, fh, anims: {name -> {row, frames, dur[], loop}}}

const SHEETS := {
	"ground": {
		"file": "ground.png",
		"fw": 16,
		"fh": 16,
		"anims": {
			"top": {
				"row": 0,
				"frames": 4,
				"dur": [
					0,
					0,
					0,
					0
				],
				"loop": true
			},
			"mid": {
				"row": 1,
				"frames": 4,
				"dur": [
					0,
					0,
					0,
					0
				],
				"loop": true
			},
			"deep": {
				"row": 2,
				"frames": 4,
				"dur": [
					0,
					0,
					0,
					0
				],
				"loop": true
			},
			"bottom": {
				"row": 3,
				"frames": 4,
				"dur": [
					0,
					0,
					0,
					0
				],
				"loop": true
			},
			"alt": {
				"row": 4,
				"frames": 4,
				"dur": [
					0,
					0,
					0,
					0
				],
				"loop": true
			}
		}
	},
	"block": {
		"file": "block.png",
		"fw": 16,
		"fh": 16,
		"anims": {
			"lip": {
				"row": 0,
				"frames": 4,
				"dur": [
					0,
					0,
					0,
					0
				],
				"loop": true
			},
			"stacked": {
				"row": 1,
				"frames": 4,
				"dur": [
					0,
					0,
					0,
					0
				],
				"loop": true
			}
		}
	},
	"girder": {
		"file": "girder.png",
		"fw": 16,
		"fh": 16,
		"anims": {
			"static": {
				"row": 0,
				"frames": 4,
				"dur": [
					0,
					0,
					0,
					0
				],
				"loop": true
			}
		}
	},
	"moving_girder": {
		"file": "moving_girder.png",
		"fw": 16,
		"fh": 16,
		"anims": {
			"left": {
				"row": 0,
				"frames": 4,
				"dur": [
					0.08,
					0.08,
					0.08,
					0.08
				],
				"loop": true
			},
			"middle": {
				"row": 1,
				"frames": 4,
				"dur": [
					0.08,
					0.08,
					0.08,
					0.08
				],
				"loop": true
			},
			"right": {
				"row": 2,
				"frames": 4,
				"dur": [
					0.08,
					0.08,
					0.08,
					0.08
				],
				"loop": true
			}
		}
	},
	"bump_block": {
		"file": "bump_block.png",
		"fw": 16,
		"fh": 16,
		"anims": {
			"shard": {
				"row": 0,
				"frames": 4,
				"dur": [
					1.1,
					0.06,
					0.06,
					0.06
				],
				"loop": true
			},
			"charge": {
				"row": 1,
				"frames": 4,
				"dur": [
					0.12,
					0.12,
					0.12,
					0.12
				],
				"loop": true
			},
			"life": {
				"row": 2,
				"frames": 4,
				"dur": [
					0.5,
					0.08,
					0.12,
					0.08
				],
				"loop": true
			},
			"hit": {
				"row": 3,
				"frames": 4,
				"dur": [
					0.05,
					0.06,
					0.1,
					0.1
				],
				"loop": false
			},
			"used": {
				"row": 4,
				"frames": 1,
				"dur": [
					0
				],
				"loop": true
			}
		}
	},
	"hidden_block": {
		"file": "hidden_block.png",
		"fw": 16,
		"fh": 16,
		"anims": {
			"hidden": {
				"row": 0,
				"frames": 1,
				"dur": [
					0
				],
				"loop": true
			},
			"reveal": {
				"row": 1,
				"frames": 4,
				"dur": [
					0.05,
					0.07,
					0.12,
					0.1
				],
				"loop": false
			}
		}
	},
	"brick": {
		"file": "brick.png",
		"fw": 16,
		"fh": 16,
		"anims": {
			"idle": {
				"row": 0,
				"frames": 1,
				"dur": [
					0
				],
				"loop": true
			},
			"bumped": {
				"row": 1,
				"frames": 2,
				"dur": [
					0.08,
					0.1
				],
				"loop": false
			},
			"break": {
				"row": 2,
				"frames": 2,
				"dur": [
					0.04,
					0.04
				],
				"loop": false
			}
		}
	},
	"brick_debris": {
		"file": "brick_debris.png",
		"fw": 8,
		"fh": 8,
		"anims": {
			"spin": {
				"row": 0,
				"frames": 4,
				"dur": [
					0.06,
					0.06,
					0.06,
					0.06
				],
				"loop": true
			}
		}
	},
	"loose_floor": {
		"file": "loose_floor.png",
		"fw": 16,
		"fh": 16,
		"anims": {
			"still": {
				"row": 0,
				"frames": 1,
				"dur": [
					0
				],
				"loop": true
			},
			"shake": {
				"row": 1,
				"frames": 2,
				"dur": [
					0.06,
					0.06
				],
				"loop": true
			},
			"fall": {
				"row": 2,
				"frames": 1,
				"dur": [
					0
				],
				"loop": true
			},
			"rubble": {
				"row": 3,
				"frames": 2,
				"dur": [
					0,
					0
				],
				"loop": true
			}
		}
	},
	"bridge": {
		"file": "bridge.png",
		"fw": 16,
		"fh": 16,
		"anims": {
			"intact": {
				"row": 0,
				"frames": 1,
				"dur": [
					0
				],
				"loop": true
			},
			"stress": {
				"row": 1,
				"frames": 2,
				"dur": [
					0.05,
					0.05
				],
				"loop": true
			},
			"snap": {
				"row": 2,
				"frames": 1,
				"dur": [
					0
				],
				"loop": true
			},
			"plank": {
				"row": 3,
				"frames": 4,
				"dur": [
					0.07,
					0.07,
					0.07,
					0.07
				],
				"loop": true
			}
		}
	},
	"spikes": {
		"file": "spikes.png",
		"fw": 16,
		"fh": 16,
		"anims": {
			"floor": {
				"row": 0,
				"frames": 3,
				"dur": [
					0.16,
					0.16,
					0.08
				],
				"loop": true
			},
			"ceiling": {
				"row": 1,
				"frames": 3,
				"dur": [
					0.16,
					0.16,
					0.08
				],
				"loop": true
			}
		}
	},
	"spike_vent": {
		"file": "spike_vent.png",
		"fw": 16,
		"fh": 16,
		"anims": {
			"down": {
				"row": 0,
				"frames": 1,
				"dur": [
					0
				],
				"loop": true
			},
			"warn": {
				"row": 1,
				"frames": 2,
				"dur": [
					0.07,
					0.07
				],
				"loop": true
			},
			"rise": {
				"row": 2,
				"frames": 2,
				"dur": [
					0.04,
					0.04
				],
				"loop": false
			},
			"up": {
				"row": 3,
				"frames": 2,
				"dur": [
					0.2,
					0.06
				],
				"loop": true
			},
			"retract": {
				"row": 4,
				"frames": 2,
				"dur": [
					0.05,
					0.05
				],
				"loop": false
			}
		}
	},
	"loose_ceiling": {
		"file": "loose_ceiling.png",
		"fw": 16,
		"fh": 16,
		"anims": {
			"intact": {
				"row": 0,
				"frames": 1,
				"dur": [
					0
				],
				"loop": true
			},
			"crack": {
				"row": 1,
				"frames": 2,
				"dur": [
					0.05,
					0.05
				],
				"loop": true
			},
			"empty": {
				"row": 2,
				"frames": 1,
				"dur": [
					0
				],
				"loop": true
			},
			"dust": {
				"row": 3,
				"frames": 4,
				"dur": [
					0.08,
					0.08,
					0.08,
					0.08
				],
				"loop": true
			},
			"chunk": {
				"row": 4,
				"frames": 4,
				"dur": [
					0.07,
					0.07,
					0.07,
					0.07
				],
				"loop": true
			},
			"landed": {
				"row": 5,
				"frames": 1,
				"dur": [
					0
				],
				"loop": true
			}
		}
	},
	"press": {
		"file": "press.png",
		"fw": 16,
		"fh": 16,
		"anims": {
			"rest": {
				"row": 0,
				"frames": 1,
				"dur": [
					0
				],
				"loop": true
			},
			"warn": {
				"row": 1,
				"frames": 2,
				"dur": [
					0.05,
					0.05
				],
				"loop": true
			},
			"slam": {
				"row": 2,
				"frames": 1,
				"dur": [
					0
				],
				"loop": true
			},
			"hold": {
				"row": 3,
				"frames": 1,
				"dur": [
					0
				],
				"loop": true
			},
			"shaft": {
				"row": 4,
				"frames": 2,
				"dur": [
					0,
					0
				],
				"loop": true
			}
		}
	},
	"press_dust": {
		"file": "press_dust.png",
		"fw": 48,
		"fh": 16,
		"anims": {
			"puff": {
				"row": 0,
				"frames": 4,
				"dur": [
					0.04,
					0.06,
					0.08,
					0.1
				],
				"loop": false
			}
		}
	},
	"dropper": {
		"file": "dropper.png",
		"fw": 32,
		"fh": 32,
		"anims": {
			"idle": {
				"row": 0,
				"frames": 3,
				"dur": [
					2.0,
					0.1,
					0.4
				],
				"loop": true
			},
			"tell": {
				"row": 1,
				"frames": 2,
				"dur": [
					0.06,
					0.06
				],
				"loop": true
			},
			"fall": {
				"row": 2,
				"frames": 1,
				"dur": [
					0
				],
				"loop": true
			},
			"land": {
				"row": 3,
				"frames": 2,
				"dur": [
					0.1,
					0.1
				],
				"loop": false
			},
			"rise": {
				"row": 4,
				"frames": 2,
				"dur": [
					0.3,
					0.3
				],
				"loop": true
			}
		}
	},
	"plate": {
		"file": "plate.png",
		"fw": 16,
		"fh": 16,
		"anims": {
			"up": {
				"row": 0,
				"frames": 1,
				"dur": [
					0
				],
				"loop": true
			},
			"press": {
				"row": 1,
				"frames": 2,
				"dur": [
					0.04,
					0.04
				],
				"loop": false
			},
			"down": {
				"row": 2,
				"frames": 1,
				"dur": [
					0
				],
				"loop": true
			},
			"release": {
				"row": 3,
				"frames": 2,
				"dur": [
					0.05,
					0.05
				],
				"loop": false
			}
		}
	},
	"gate": {
		"file": "gate.png",
		"fw": 16,
		"fh": 16,
		"anims": {
			"pieces": {
				"row": 0,
				"frames": 2,
				"dur": [
					0,
					0
				],
				"loop": true
			},
			"cap_closed": {
				"row": 1,
				"frames": 1,
				"dur": [
					0
				],
				"loop": true
			},
			"cap_opening": {
				"row": 2,
				"frames": 2,
				"dur": [
					0.06,
					0.06
				],
				"loop": true
			},
			"cap_open": {
				"row": 3,
				"frames": 1,
				"dur": [
					0
				],
				"loop": true
			}
		}
	},
	"lever": {
		"file": "lever.png",
		"fw": 16,
		"fh": 16,
		"anims": {
			"off": {
				"row": 0,
				"frames": 1,
				"dur": [
					0
				],
				"loop": true
			},
			"pull": {
				"row": 1,
				"frames": 3,
				"dur": [
					0.05,
					0.06,
					0.1
				],
				"loop": false
			},
			"on": {
				"row": 2,
				"frames": 1,
				"dur": [
					0
				],
				"loop": true
			}
		}
	},
	"spring": {
		"file": "spring.png",
		"fw": 16,
		"fh": 16,
		"anims": {
			"rest": {
				"row": 0,
				"frames": 1,
				"dur": [
					0
				],
				"loop": true
			},
			"bounce": {
				"row": 1,
				"frames": 3,
				"dur": [
					0.05,
					0.08,
					0.1
				],
				"loop": false
			}
		}
	},
	"lift_ring": {
		"file": "lift_ring.png",
		"fw": 24,
		"fh": 24,
		"anims": {
			"idle": {
				"row": 0,
				"frames": 4,
				"dur": [
					0.1,
					0.1,
					0.1,
					0.1
				],
				"loop": true
			},
			"pop": {
				"row": 1,
				"frames": 2,
				"dur": [
					0.06,
					0.1
				],
				"loop": false
			},
			"used": {
				"row": 2,
				"frames": 1,
				"dur": [
					0
				],
				"loop": true
			}
		}
	},
	"shard": {
		"file": "shard.png",
		"fw": 16,
		"fh": 16,
		"anims": {
			"spin": {
				"row": 0,
				"frames": 6,
				"dur": [
					0.4,
					0.08,
					0.06,
					0.05,
					0.06,
					0.08
				],
				"loop": true
			}
		}
	},
	"big_shard": {
		"file": "big_shard.png",
		"fw": 24,
		"fh": 24,
		"anims": {
			"spin": {
				"row": 0,
				"frames": 6,
				"dur": [
					0.5,
					0.08,
					0.06,
					0.05,
					0.06,
					0.08
				],
				"loop": true
			}
		}
	},
	"pickups": {
		"file": "pickups.png",
		"fw": 16,
		"fh": 16,
		"anims": {
			"charge": {
				"row": 0,
				"frames": 4,
				"dur": [
					0.08,
					0.08,
					0.08,
					0.08
				],
				"loop": true
			},
			"life": {
				"row": 1,
				"frames": 2,
				"dur": [
					0.2,
					0.2
				],
				"loop": true
			}
		}
	},
	"walker": {
		"file": "walker.png",
		"fw": 16,
		"fh": 16,
		"anims": {
			"walk": {
				"row": 0,
				"frames": 4,
				"dur": [
					0.12,
					0.12,
					0.12,
					0.12
				],
				"loop": true
			},
			"turn": {
				"row": 1,
				"frames": 2,
				"dur": [
					0.06,
					0.06
				],
				"loop": true
			},
			"stomped": {
				"row": 2,
				"frames": 1,
				"dur": [
					0
				],
				"loop": true
			}
		}
	},
	"hopper": {
		"file": "hopper.png",
		"fw": 16,
		"fh": 16,
		"anims": {
			"idle": {
				"row": 0,
				"frames": 2,
				"dur": [
					0.2,
					0.2
				],
				"loop": true
			},
			"crouch": {
				"row": 1,
				"frames": 3,
				"dur": [
					0.08,
					0.08,
					0.08
				],
				"loop": true
			},
			"jump": {
				"row": 2,
				"frames": 1,
				"dur": [
					0
				],
				"loop": true
			},
			"fall": {
				"row": 3,
				"frames": 1,
				"dur": [
					0
				],
				"loop": true
			},
			"land": {
				"row": 4,
				"frames": 1,
				"dur": [
					0.08
				],
				"loop": false
			},
			"stomped": {
				"row": 5,
				"frames": 1,
				"dur": [
					0
				],
				"loop": true
			}
		}
	},
	"warden": {
		"file": "warden.png",
		"fw": 32,
		"fh": 32,
		"anims": {
			"walk": {
				"row": 0,
				"frames": 4,
				"dur": [
					0.16,
					0.16,
					0.16,
					0.16
				],
				"loop": true
			},
			"hop_tell": {
				"row": 1,
				"frames": 3,
				"dur": [
					0.08,
					0.08,
					0.08
				],
				"loop": true
			},
			"hop": {
				"row": 2,
				"frames": 1,
				"dur": [
					0
				],
				"loop": true
			},
			"fall": {
				"row": 3,
				"frames": 2,
				"dur": [
					0.1,
					0.1
				],
				"loop": true
			},
			"hurt": {
				"row": 4,
				"frames": 2,
				"dur": [
					0.06,
					0.06
				],
				"loop": true
			}
		}
	},
	"pipe": {
		"file": "pipe.png",
		"fw": 32,
		"fh": 16,
		"anims": {
			"mouth": {
				"row": 0,
				"frames": 2,
				"dur": [
					0.6,
					0.15
				],
				"loop": true
			},
			"body": {
				"row": 1,
				"frames": 1,
				"dur": [
					0
				],
				"loop": true
			}
		}
	},
	"beacon": {
		"file": "beacon.png",
		"fw": 16,
		"fh": 32,
		"anims": {
			"dark": {
				"row": 0,
				"frames": 1,
				"dur": [
					0
				],
				"loop": true
			},
			"ignite": {
				"row": 1,
				"frames": 2,
				"dur": [
					0.05,
					0.08
				],
				"loop": false
			},
			"lit": {
				"row": 2,
				"frames": 3,
				"dur": [
					0.15,
					0.15,
					0.15
				],
				"loop": true
			}
		}
	},
	"mast": {
		"file": "mast.png",
		"fw": 16,
		"fh": 16,
		"anims": {
			"pieces": {
				"row": 0,
				"frames": 3,
				"dur": [
					0,
					0,
					0
				],
				"loop": true
			},
			"top_lit": {
				"row": 1,
				"frames": 2,
				"dur": [
					0.2,
					0.2
				],
				"loop": true
			},
			"base_lit": {
				"row": 2,
				"frames": 1,
				"dur": [
					0
				],
				"loop": true
			}
		}
	},
	"mast_flag": {
		"file": "mast_flag.png",
		"fw": 24,
		"fh": 16,
		"anims": {
			"wave": {
				"row": 0,
				"frames": 4,
				"dur": [
					0.14,
					0.14,
					0.14,
					0.14
				],
				"loop": true
			},
			"lit": {
				"row": 1,
				"frames": 4,
				"dur": [
					0.08,
					0.08,
					0.08,
					0.08
				],
				"loop": true
			}
		}
	},
	"gate_transmitter": {
		"file": "gate_transmitter.png",
		"fw": 128,
		"fh": 224,
		"anims": {
			"dormant": {
				"row": 0,
				"frames": 4,
				"dur": [
					3.2,
					0.07,
					0.07,
					0.09
				],
				"loop": true
			},
			"awake": {
				"row": 1,
				"frames": 4,
				"dur": [
					0.8,
					0.07,
					0.07,
					0.09
				],
				"loop": true
			}
		}
	},
	"fx_dust": {
		"file": "fx_dust.png",
		"fw": 16,
		"fh": 8,
		"anims": {
			"land": {
				"row": 0,
				"frames": 5,
				"dur": [
					0.04,
					0.04,
					0.04,
					0.04,
					0.04
				],
				"loop": false
			}
		}
	},
	"fx_skid": {
		"file": "fx_skid.png",
		"fw": 8,
		"fh": 8,
		"anims": {
			"skid": {
				"row": 0,
				"frames": 4,
				"dur": [
					0.04,
					0.04,
					0.04,
					0.04
				],
				"loop": false
			}
		}
	},
	"fx_burst": {
		"file": "fx_burst.png",
		"fw": 32,
		"fh": 32,
		"anims": {
			"stomp": {
				"row": 0,
				"frames": 5,
				"dur": [
					0.03,
					0.04,
					0.05,
					0.06,
					0.06
				],
				"loop": false
			}
		}
	},
	"fx_sparkle": {
		"file": "fx_sparkle.png",
		"fw": 8,
		"fh": 8,
		"anims": {
			"twinkle": {
				"row": 0,
				"frames": 4,
				"dur": [
					0.06,
					0.06,
					0.06,
					0.06
				],
				"loop": false
			}
		}
	},
	"fx_charge_glow": {
		"file": "fx_charge_glow.png",
		"fw": 24,
		"fh": 24,
		"anims": {
			"glow": {
				"row": 0,
				"frames": 4,
				"dur": [
					0.07,
					0.07,
					0.07,
					0.07
				],
				"loop": true
			}
		}
	},
	"fx_light": {
		"file": "fx_light.png",
		"fw": 48,
		"fh": 48,
		"anims": {
			"ring": {
				"row": 0,
				"frames": 5,
				"dur": [
					0.05,
					0.05,
					0.05,
					0.05,
					0.05
				],
				"loop": false
			}
		}
	},
	"fx_hint": {
		"file": "fx_hint.png",
		"fw": 8,
		"fh": 8,
		"anims": {
			"down": {
				"row": 0,
				"frames": 2,
				"dur": [
					0.3,
					0.3
				],
				"loop": true
			}
		}
	},
	"channel_block": {
		"file": "channel_block.png",
		"fw": 16,
		"fh": 16,
		"anims": {
			"one_solid": {
				"row": 0,
				"frames": 1,
				"dur": [
					0
				],
				"loop": true
			},
			"one_off": {
				"row": 1,
				"frames": 1,
				"dur": [
					0
				],
				"loop": true
			},
			"one_arm": {
				"row": 2,
				"frames": 3,
				"dur": [
					0.1,
					0.1,
					0.1
				],
				"loop": true
			},
			"two_solid": {
				"row": 3,
				"frames": 1,
				"dur": [
					0
				],
				"loop": true
			},
			"two_off": {
				"row": 4,
				"frames": 1,
				"dur": [
					0
				],
				"loop": true
			},
			"two_arm": {
				"row": 5,
				"frames": 3,
				"dur": [
					0.1,
					0.1,
					0.1
				],
				"loop": true
			}
		}
	},
	"channel_switch": {
		"file": "channel_switch.png",
		"fw": 16,
		"fh": 16,
		"anims": {
			"one": {
				"row": 0,
				"frames": 2,
				"dur": [
					0.45,
					0.45
				],
				"loop": true
			},
			"two": {
				"row": 1,
				"frames": 2,
				"dur": [
					0.45,
					0.45
				],
				"loop": true
			},
			"hit": {
				"row": 2,
				"frames": 3,
				"dur": [
					0.05,
					0.05,
					0.05
				],
				"loop": false
			}
		}
	},
	"spiky": {
		"file": "spiky.png",
		"fw": 16,
		"fh": 16,
		"anims": {
			"walk": {
				"row": 0,
				"frames": 4,
				"dur": [
					0.12,
					0.12,
					0.12,
					0.12
				],
				"loop": true
			},
			"turn": {
				"row": 1,
				"frames": 2,
				"dur": [
					0.06,
					0.06
				],
				"loop": true
			},
			"knocked": {
				"row": 2,
				"frames": 1,
				"dur": [
					0
				],
				"loop": true
			},
			"fall": {
				"row": 3,
				"frames": 1,
				"dur": [
					0
				],
				"loop": true
			}
		}
	},
	"fuse": {
		"file": "fuse.png",
		"fw": 16,
		"fh": 16,
		"anims": {
			"live": {
				"row": 0,
				"frames": 2,
				"dur": [
					0.3,
					0.3
				],
				"loop": true
			},
			"blow": {
				"row": 1,
				"frames": 4,
				"dur": [
					0.06,
					0.06,
					0.06,
					0.06
				],
				"loop": false
			},
			"blown": {
				"row": 2,
				"frames": 1,
				"dur": [
					0
				],
				"loop": true
			}
		}
	},
	"relay": {
		"file": "relay.png",
		"fw": 48,
		"fh": 48,
		"anims": {
			"idle": {
				"row": 0,
				"frames": 4,
				"dur": [
					0.12,
					0.12,
					0.12,
					0.12
				],
				"loop": true
			},
			"tell": {
				"row": 1,
				"frames": 3,
				"dur": [
					0.1,
					0.1,
					0.1
				],
				"loop": true
			},
			"swap": {
				"row": 2,
				"frames": 2,
				"dur": [
					0.05,
					0.05
				],
				"loop": false
			},
			"lamps": {
				"row": 3,
				"frames": 4,
				"dur": [
					0,
					0,
					0,
					0
				],
				"loop": true
			},
			"overload": {
				"row": 4,
				"frames": 6,
				"dur": [
					0.08,
					0.08,
					0.08,
					0.08,
					0.08,
					0.08
				],
				"loop": false
			},
			"dead": {
				"row": 5,
				"frames": 1,
				"dur": [
					0
				],
				"loop": true
			}
		}
	},
	"ground_w2": {
		"file": "ground_w2.png",
		"fw": 16,
		"fh": 16,
		"anims": {
			"top": {
				"row": 0,
				"frames": 4,
				"dur": [
					0,
					0,
					0,
					0
				],
				"loop": true
			},
			"mid": {
				"row": 1,
				"frames": 4,
				"dur": [
					0,
					0,
					0,
					0
				],
				"loop": true
			},
			"deep": {
				"row": 2,
				"frames": 4,
				"dur": [
					0,
					0,
					0,
					0
				],
				"loop": true
			},
			"bottom": {
				"row": 3,
				"frames": 4,
				"dur": [
					0,
					0,
					0,
					0
				],
				"loop": true
			},
			"alt": {
				"row": 4,
				"frames": 4,
				"dur": [
					0,
					0,
					0,
					0
				],
				"loop": true
			}
		}
	},
	"block_w2": {
		"file": "block_w2.png",
		"fw": 16,
		"fh": 16,
		"anims": {
			"lip": {
				"row": 0,
				"frames": 4,
				"dur": [
					0,
					0,
					0,
					0
				],
				"loop": true
			},
			"stacked": {
				"row": 1,
				"frames": 4,
				"dur": [
					0,
					0,
					0,
					0
				],
				"loop": true
			}
		}
	},
	"backdrop_w2": {
		"file": "backdrop_w2.png",
		"fw": 96,
		"fh": 128,
		"anims": {
			"pieces": {
				"row": 0,
				"frames": 4,
				"dur": [
					0,
					0,
					0,
					0
				],
				"loop": true
			}
		}
	},
	"lamp": {
		"file": "lamp.png",
		"fw": 16,
		"fh": 32,
		"anims": {
			"off": {
				"row": 0,
				"frames": 1,
				"dur": [
					0
				],
				"loop": true
			},
			"ignite": {
				"row": 1,
				"frames": 5,
				"dur": [
					0.05,
					0.05,
					0.05,
					0.05,
					0.05
				],
				"loop": false
			},
			"on": {
				"row": 2,
				"frames": 4,
				"dur": [
					0.15,
					0.15,
					0.15,
					0.15
				],
				"loop": true
			}
		}
	},
	"light_mask": {
		"file": "light_mask.png",
		"fw": 256,
		"fh": 256,
		"anims": {
			"disc": {
				"row": 0,
				"frames": 3,
				"dur": [
					0,
					0,
					0
				],
				"loop": true
			}
		}
	},
	"weather": {
		"file": "weather.png",
		"fw": 16,
		"fh": 16,
		"anims": {
			"rain": {
				"row": 0,
				"frames": 4,
				"dur": [
					0,
					0,
					0,
					0
				],
				"loop": true
			},
			"static": {
				"row": 1,
				"frames": 4,
				"dur": [
					0,
					0,
					0,
					0
				],
				"loop": true
			},
			"splash": {
				"row": 2,
				"frames": 3,
				"dur": [
					0.05,
					0.05,
					0.05
				],
				"loop": false
			}
		}
	},
	"fog": {
		"file": "fog.png",
		"fw": 32,
		"fh": 16,
		"anims": {
			"band": {
				"row": 0,
				"frames": 4,
				"dur": [
					0,
					0,
					0,
					0
				],
				"loop": true
			}
		}
	},
	"npc": {
		"file": "npc.png",
		"fw": 16,
		"fh": 24,
		"anims": {
			"mast_idle": {
				"row": 0,
				"frames": 4,
				"dur": [
					0.2,
					0.2,
					0.2,
					0.2
				],
				"loop": true
			},
			"mast_talk": {
				"row": 1,
				"frames": 2,
				"dur": [
					0.12,
					0.12
				],
				"loop": true
			},
			"tally_idle": {
				"row": 2,
				"frames": 4,
				"dur": [
					0.2,
					0.2,
					0.2,
					0.2
				],
				"loop": true
			},
			"tally_talk": {
				"row": 3,
				"frames": 2,
				"dur": [
					0.12,
					0.12
				],
				"loop": true
			},
			"wren_idle": {
				"row": 4,
				"frames": 4,
				"dur": [
					0.2,
					0.2,
					0.2,
					0.2
				],
				"loop": true
			},
			"wren_talk": {
				"row": 5,
				"frames": 2,
				"dur": [
					0.12,
					0.12
				],
				"loop": true
			},
			"brace_idle": {
				"row": 6,
				"frames": 4,
				"dur": [
					0.2,
					0.2,
					0.2,
					0.2
				],
				"loop": true
			},
			"brace_talk": {
				"row": 7,
				"frames": 2,
				"dur": [
					0.12,
					0.12
				],
				"loop": true
			},
			"dot_idle": {
				"row": 8,
				"frames": 4,
				"dur": [
					0.2,
					0.2,
					0.2,
					0.2
				],
				"loop": true
			},
			"dot_talk": {
				"row": 9,
				"frames": 2,
				"dur": [
					0.12,
					0.12
				],
				"loop": true
			},
			"hum_idle": {
				"row": 10,
				"frames": 4,
				"dur": [
					0.2,
					0.2,
					0.2,
					0.2
				],
				"loop": true
			},
			"hum_talk": {
				"row": 11,
				"frames": 2,
				"dur": [
					0.12,
					0.12
				],
				"loop": true
			},
			"spire_idle": {
				"row": 12,
				"frames": 4,
				"dur": [
					0.2,
					0.2,
					0.2,
					0.2
				],
				"loop": true
			},
			"spire_talk": {
				"row": 13,
				"frames": 2,
				"dur": [
					0.12,
					0.12
				],
				"loop": true
			}
		}
	},
	"house": {
		"file": "house.png",
		"fw": 64,
		"fh": 64,
		"anims": {
			"facades": {
				"row": 0,
				"frames": 5,
				"dur": [
					0,
					0,
					0,
					0,
					0
				],
				"loop": true
			},
			"door": {
				"row": 1,
				"frames": 2,
				"dur": [
					0,
					0
				],
				"loop": true
			}
		}
	},
	"interior": {
		"file": "interior.png",
		"fw": 16,
		"fh": 16,
		"anims": {
			"tiles": {
				"row": 0,
				"frames": 11,
				"dur": [
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0
				],
				"loop": true
			}
		}
	},
	"bubble": {
		"file": "bubble.png",
		"fw": 16,
		"fh": 16,
		"anims": {
			"parts": {
				"row": 0,
				"frames": 10,
				"dur": [
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0,
					0
				],
				"loop": true
			},
			"prompt": {
				"row": 1,
				"frames": 2,
				"dur": [
					0.4,
					0.4
				],
				"loop": true
			}
		}
	},
	"switchboard": {
		"file": "switchboard.png",
		"fw": 32,
		"fh": 32,
		"anims": {
			"idle": {
				"row": 0,
				"frames": 2,
				"dur": [
					0.5,
					0.5
				],
				"loop": true
			},
			"use": {
				"row": 1,
				"frames": 3,
				"dur": [
					0.08,
					0.08,
					0.08
				],
				"loop": false
			}
		}
	},
	"shop_items": {
		"file": "shop_items.png",
		"fw": 16,
		"fh": 16,
		"anims": {
			"icons": {
				"row": 0,
				"frames": 5,
				"dur": [
					0,
					0,
					0,
					0,
					0
				],
				"loop": true
			}
		}
	},
	"village_props": {
		"file": "village_props.png",
		"fw": 16,
		"fh": 16,
		"anims": {
			"props": {
				"row": 0,
				"frames": 6,
				"dur": [
					0,
					0,
					0,
					0,
					0,
					0
				],
				"loop": true
			}
		}
	},
	"backdrop_village": {
		"file": "backdrop_village.png",
		"fw": 96,
		"fh": 128,
		"anims": {
			"pieces": {
				"row": 0,
				"frames": 4,
				"dur": [
					0,
					0,
					0,
					0
				],
				"loop": true
			}
		}
	},
	"ground_w3": {
		"file": "ground_w3.png",
		"fw": 16,
		"fh": 16,
		"anims": {
			"top": {
				"row": 0,
				"frames": 4,
				"dur": [
					0,
					0,
					0,
					0
				],
				"loop": true
			},
			"mid": {
				"row": 1,
				"frames": 4,
				"dur": [
					0,
					0,
					0,
					0
				],
				"loop": true
			},
			"deep": {
				"row": 2,
				"frames": 4,
				"dur": [
					0,
					0,
					0,
					0
				],
				"loop": true
			},
			"bottom": {
				"row": 3,
				"frames": 4,
				"dur": [
					0,
					0,
					0,
					0
				],
				"loop": true
			},
			"alt": {
				"row": 4,
				"frames": 4,
				"dur": [
					0,
					0,
					0,
					0
				],
				"loop": true
			}
		}
	},
	"block_w3": {
		"file": "block_w3.png",
		"fw": 16,
		"fh": 16,
		"anims": {
			"lip": {
				"row": 0,
				"frames": 4,
				"dur": [
					0,
					0,
					0,
					0
				],
				"loop": true
			},
			"stacked": {
				"row": 1,
				"frames": 4,
				"dur": [
					0,
					0,
					0,
					0
				],
				"loop": true
			}
		}
	},
	"backdrop_w3": {
		"file": "backdrop_w3.png",
		"fw": 96,
		"fh": 128,
		"anims": {
			"pieces": {
				"row": 0,
				"frames": 4,
				"dur": [
					0,
					0,
					0,
					0
				],
				"loop": true
			}
		}
	},
	"flyer": {
		"file": "flyer.png",
		"fw": 16,
		"fh": 16,
		"anims": {
			"fly": {
				"row": 0,
				"frames": 4,
				"dur": [
					0.1,
					0.1,
					0.1,
					0.1
				],
				"loop": true
			},
			"turn": {
				"row": 1,
				"frames": 2,
				"dur": [
					0.06,
					0.06
				],
				"loop": true
			},
			"stomped": {
				"row": 2,
				"frames": 1,
				"dur": [
					0
				],
				"loop": true
			}
		}
	},
	"sweep_arm": {
		"file": "sweep_arm.png",
		"fw": 16,
		"fh": 16,
		"anims": {
			"pivot": {
				"row": 0,
				"frames": 2,
				"dur": [
					0.25,
					0.25
				],
				"loop": true
			},
			"dot": {
				"row": 1,
				"frames": 2,
				"dur": [
					0.08,
					0.08
				],
				"loop": true
			}
		}
	},
	"wind": {
		"file": "wind.png",
		"fw": 16,
		"fh": 16,
		"anims": {
			"side": {
				"row": 0,
				"frames": 4,
				"dur": [
					0.07,
					0.07,
					0.07,
					0.07
				],
				"loop": true
			},
			"up": {
				"row": 1,
				"frames": 4,
				"dur": [
					0.07,
					0.07,
					0.07,
					0.07
				],
				"loop": true
			},
			"gust_tell": {
				"row": 2,
				"frames": 3,
				"dur": [
					0.15,
					0.15,
					0.15
				],
				"loop": false
			}
		}
	},
	"wind_vane": {
		"file": "wind_vane.png",
		"fw": 16,
		"fh": 32,
		"anims": {
			"spin": {
				"row": 0,
				"frames": 4,
				"dur": [
					0.08,
					0.08,
					0.08,
					0.08
				],
				"loop": true
			},
			"still": {
				"row": 1,
				"frames": 1,
				"dur": [
					0
				],
				"loop": true
			}
		}
	},
	"title_logo": {
		"file": "title_logo.png",
		"fw": 240,
		"fh": 44,
		"anims": {
			"unlit": {
				"row": 0,
				"frames": 1,
				"dur": [
					0
				],
				"loop": true
			},
			"lit": {
				"row": 1,
				"frames": 1,
				"dur": [
					0
				],
				"loop": true
			},
			"glow": {
				"row": 2,
				"frames": 1,
				"dur": [
					0
				],
				"loop": true
			}
		}
	},
	"title_logo_antenna": {
		"file": "title_logo_antenna.png",
		"fw": 24,
		"fh": 12,
		"anims": {
			"pulse": {
				"row": 0,
				"frames": 5,
				"dur": [
					0.32,
					0.32,
					0.32,
					0.64,
					0.07
				],
				"loop": true
			},
			"steady": {
				"row": 1,
				"frames": 1,
				"dur": [
					0
				],
				"loop": true
			}
		}
	},
	"title_scene": {
		"file": "title_scene.png",
		"fw": 320,
		"fh": 64,
		"anims": {
			"far": {
				"row": 0,
				"frames": 1,
				"dur": [
					0
				],
				"loop": true
			},
			"mid": {
				"row": 1,
				"frames": 1,
				"dur": [
					0
				],
				"loop": true
			}
		}
	},
	"title_pole": {
		"file": "title_pole.png",
		"fw": 24,
		"fh": 64,
		"anims": {
			"pole": {
				"row": 0,
				"frames": 2,
				"dur": [
					0,
					0
				],
				"loop": true
			}
		}
	},
	"title_caller": {
		"file": "title_caller.png",
		"fw": 8,
		"fh": 8,
		"anims": {
			"blink": {
				"row": 0,
				"frames": 4,
				"dur": [
					3.0,
					0.08,
					0.16,
					0.1
				],
				"loop": true
			},
			"blink_gray": {
				"row": 1,
				"frames": 4,
				"dur": [
					3.0,
					0.08,
					0.16,
					0.1
				],
				"loop": true
			}
		}
	},
	"arc": {
		"file": "arc.png",
		"fw": 24,
		"fh": 16,
		"anims": {
			"swing": {
				"row": 0,
				"frames": 4,
				"dur": [
					0.02,
					0.04,
					0.06,
					0.08
				],
				"loop": false
			}
		}
	},
	"arc_hit": {
		"file": "arc_hit.png",
		"fw": 16,
		"fh": 16,
		"anims": {
			"hit": {
				"row": 0,
				"frames": 3,
				"dur": [
					0.03,
					0.05,
					0.07
				],
				"loop": false
			}
		}
	},
	"crack": {
		"file": "crack.png",
		"fw": 16,
		"fh": 16,
		"anims": {
			"w1": {
				"row": 0,
				"frames": 4,
				"dur": [
					0,
					0,
					0,
					0
				],
				"loop": true
			},
			"w2": {
				"row": 1,
				"frames": 4,
				"dur": [
					0,
					0,
					0,
					0
				],
				"loop": true
			},
			"w3": {
				"row": 2,
				"frames": 4,
				"dur": [
					0,
					0,
					0,
					0
				],
				"loop": true
			},
			"break": {
				"row": 3,
				"frames": 4,
				"dur": [
					0.04,
					0.06,
					0.08,
					0.1
				],
				"loop": false
			}
		}
	},
	"arc_icon": {
		"file": "arc_icon.png",
		"fw": 16,
		"fh": 16,
		"anims": {
			"hud": {
				"row": 0,
				"frames": 2,
				"dur": [
					0,
					0
				],
				"loop": true
			},
			"pickup": {
				"row": 1,
				"frames": 4,
				"dur": [
					0.1,
					0.1,
					0.1,
					0.1
				],
				"loop": true
			}
		}
	},
	"intro_npc": {
		"file": "intro_npc.png",
		"fw": 16,
		"fh": 24,
		"anims": {
			"listener_sit": {
				"row": 0,
				"frames": 2,
				"dur": [
					0,
					0
				],
				"loop": true
			},
			"mast_lantern_walk": {
				"row": 1,
				"frames": 4,
				"dur": [
					0.2,
					0.2,
					0.2,
					0.2
				],
				"loop": true
			},
			"mast_lantern_stand": {
				"row": 2,
				"frames": 2,
				"dur": [
					0.4,
					0.4
				],
				"loop": true
			},
			"mast_lantern_look": {
				"row": 3,
				"frames": 2,
				"dur": [
					0.5,
					0.5
				],
				"loop": true
			}
		}
	},
	"intro_poles": {
		"file": "intro_poles.png",
		"fw": 48,
		"fh": 64,
		"anims": {
			"switch_ready": {
				"row": 0,
				"frames": 2,
				"dur": [
					0.5,
					0.5
				],
				"loop": true
			},
			"switch_pull": {
				"row": 1,
				"frames": 5,
				"dur": [
					0.1,
					0.1,
					0.15,
					0.1,
					0.25
				],
				"loop": false
			},
			"switch_after": {
				"row": 2,
				"frames": 2,
				"dur": [
					0.6,
					0.6
				],
				"loop": true
			},
			"dead": {
				"row": 3,
				"frames": 3,
				"dur": [
					0,
					0,
					0
				],
				"loop": true
			}
		}
	},
	"intro_static": {
		"file": "intro_static.png",
		"fw": 32,
		"fh": 16,
		"anims": {
			"crawl": {
				"row": 0,
				"frames": 4,
				"dur": [
					0.06,
					0.06,
					0.06,
					0.06
				],
				"loop": true
			},
			"stall": {
				"row": 1,
				"frames": 3,
				"dur": [
					0.08,
					0.08,
					0.08
				],
				"loop": true
			},
			"die": {
				"row": 2,
				"frames": 4,
				"dur": [
					0.1,
					0.1,
					0.1,
					0.1
				],
				"loop": false
			}
		}
	},
	"spark_close": {
		"file": "spark_close.png",
		"fw": 48,
		"fh": 48,
		"anims": {
			"curled": {
				"row": 0,
				"frames": 2,
				"dur": [
					1.2,
					1.2
				],
				"loop": true
			},
			"stir": {
				"row": 1,
				"frames": 3,
				"dur": [
					0,
					0,
					0
				],
				"loop": true
			},
			"flare": {
				"row": 2,
				"frames": 4,
				"dur": [
					0.06,
					0.06,
					0.1,
					0.12
				],
				"loop": false
			},
			"sit": {
				"row": 3,
				"frames": 2,
				"dur": [
					0.5,
					0.5
				],
				"loop": true
			}
		}
	},
	"intro_wire_close": {
		"file": "intro_wire_close.png",
		"fw": 32,
		"fh": 32,
		"anims": {
			"grass": {
				"row": 0,
				"frames": 4,
				"dur": [
					0,
					0,
					0,
					0
				],
				"loop": true
			},
			"wire": {
				"row": 1,
				"frames": 2,
				"dur": [
					0,
					0
				],
				"loop": true
			},
			"wire_end": {
				"row": 2,
				"frames": 1,
				"dur": [
					0
				],
				"loop": true
			},
			"wire_lit": {
				"row": 3,
				"frames": 2,
				"dur": [
					0,
					0
				],
				"loop": true
			},
			"ring": {
				"row": 4,
				"frames": 3,
				"dur": [
					0.06,
					0.06,
					0.06
				],
				"loop": true
			},
			"ring_pop": {
				"row": 5,
				"frames": 3,
				"dur": [
					0.05,
					0.05,
					0.05
				],
				"loop": false
			}
		}
	},
	"intro_far": {
		"file": "intro_far.png",
		"fw": 64,
		"fh": 64,
		"anims": {
			"keeper_night": {
				"row": 0,
				"frames": 2,
				"dur": [
					0.8,
					0.15
				],
				"loop": true
			},
			"gate_far": {
				"row": 1,
				"frames": 1,
				"dur": [
					0
				],
				"loop": true
			}
		}
	},
	"intro_window": {
		"file": "intro_window.png",
		"fw": 320,
		"fh": 176,
		"anims": {
			"frame": {
				"row": 0,
				"frames": 1,
				"dur": [
					0
				],
				"loop": true
			}
		}
	},
	"title_hero": {
		"file": "title_hero.png",
		"fw": 64,
		"fh": 64,
		"anims": {
			"idle": {
				"row": 0,
				"frames": 8,
				"dur": [
					0.12,
					0.12,
					0.12,
					0.12,
					0.12,
					0.12,
					0.12,
					0.12
				],
				"loop": true
			},
			"look": {
				"row": 1,
				"frames": 8,
				"dur": [
					0.12,
					0.12,
					0.12,
					0.12,
					0.12,
					0.12,
					0.12,
					0.12
				],
				"loop": false
			},
			"leap": {
				"row": 2,
				"frames": 5,
				"dur": [
					0.1,
					0.06,
					0.1,
					0.1,
					0.1
				],
				"loop": false
			},
			"blink": {
				"row": 3,
				"frames": 8,
				"dur": [
					0.12,
					0.12,
					0.12,
					0.12,
					0.12,
					0.12,
					0.12,
					0.12
				],
				"loop": true
			},
			"answer": {
				"row": 4,
				"frames": 8,
				"dur": [
					0.12,
					0.12,
					0.12,
					0.12,
					0.12,
					0.12,
					0.12,
					0.12
				],
				"loop": true
			}
		}
	},
	"title_cliff": {
		"file": "title_cliff.png",
		"fw": 160,
		"fh": 128,
		"anims": {
			"edge": {
				"row": 0,
				"frames": 1,
				"dur": [
					0
				],
				"loop": true
			},
			"grass": {
				"row": 1,
				"frames": 4,
				"dur": [
					0.16,
					0.16,
					0.16,
					0.16
				],
				"loop": true
			},
			"fill": {
				"row": 2,
				"frames": 1,
				"dur": [
					0
				],
				"loop": true
			}
		}
	}
}
